# -*- coding: utf-8 -*-
"""print_map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iNWxfXjf-qXlhiQIvaJXevukuxJIZlSj
"""

import folium

m = folium.Map(location=[13.009711, 76.102898])
folium.Marker(
    location=[13.009711, 76.102898],
    popup='Hassan',
    icon=folium.Icon(icon='cloud')
).add_to(m)

folium.Marker(
    location=[13.209711, 76.212898],
    popup='Doddenahalli',
    icon=folium.Icon(color='green')
).add_to(m)

folium.Marker(
    location=[13.109711, 76.202898],
    popup='Dudda',
    icon=folium.Icon(color='red', icon='info-sign')
).add_to(m)
m